In [1]:
import pandas as pd
url = 'https://basketball.realgm.com/ncaa/team-stats/2022/Advanced_Stats/Team_Totals/0'
pd.read_html(url)[0]
advanced = pd.read_html(url)[0]
del advanced[advanced.columns[0]]
advanced

,Team,TS%,eFG%,Total S%,ORB%,DRB%,TRB%,AST%,TOV%,STL%,BLK%,PPS,FIC40,ORtg,DRtg,eDiff,Poss,Pace
0,Gonzaga,0.608,0.587,160.5,28.5,77.5,55.8,55.3,13.8,8.6,13.4,1.4,76.8,117.2,89.0,28.2,2381.4,74.6
1,Houston,0.551,0.531,147.0,37.2,73.3,55.1,58.5,14.1,12.0,17.1,1.3,64.2,112.6,88.4,24.2,2525.8,66.0
2,Murray State,0.567,0.542,151.8,35.1,76.1,55.9,51.2,14.1,11.4,9.5,1.3,64.0,114.3,91.3,22.9,2353.9,69.0
3,Arizona,0.587,0.556,158.3,34.3,72.4,55.3,65.0,15.8,9.1,13.4,1.4,72.7,113.7,92.1,21.5,2733.4,73.5
4,Vermont,0.594,0.570,159.9,23.4,82.0,54.6,55.0,13.2,7.7,7.2,1.3,60.3,113.6,92.2,21.4,2238.6,65.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,Chicago State,0.486,0.457,135.5,31.3,68.2,48.7,44.0,19.1,8.2,6.5,1.1,33.6,91.5,109.6,-18.1,2172.5,67.7
354,Omaha,0.525,0.492,151.7,23.7,71.2,47.0,43.4,17.1,6.7,6.9,1.2,40.8,97.0,116.3,-19.4,2153.4,71.9
355,Mississippi Valley State,0.476,0.444,134.6,23.2,65.9,42.3,48.7,16.0,9.9,6.0,1.1,37.5,90.2,111.3,-21.1,2087.4,72.9
356,Eastern Illinois,0.485,0.457,136.1,21.2,66.8,44.0,58.9,21.6,9.5,9.2,1.1,33.3,84.1,106.2,-22.1,2075.6,67.0
357,IUPUI,0.461,0.430,133.8,29.5,69.1,48.7,54.4,22.6,8.9,8.4,1.0,27.6,81.7,104.6,-22.9,1861.7,64.2

In [2]:
url = 'https://basketball.realgm.com/ncaa/team-stats/2022/Averages/Team_Totals/0'
pd.read_html(url)[0]
averages = pd.read_html(url)[0]
del averages[averages.columns[0]]
averages

,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,3P%,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
0,Gonzaga,32,39.9,87.2,32.7,62.6,0.521,8.2,22.1,0.370,...,19.2,0.713,9.2,31.3,40.4,18.1,6.4,5.8,11.5,15.5
1,South Dakota State,35,40.2,85.9,30.8,59.1,0.521,9.3,20.9,0.445,...,19.7,0.758,7.1,27.3,34.4,15.1,6.1,2.5,11.0,15.3
2,Arizona,37,40.2,84.0,30.2,61.3,0.492,7.8,22.0,0.352,...,21.4,0.739,11.2,29.0,40.2,19.6,6.7,5.7,13.4,16.7
3,Oral Roberts,31,40.3,83.3,30.2,66.2,0.456,11.6,30.6,0.379,...,15.4,0.730,10.3,28.6,38.9,11.7,5.5,4.2,9.9,15.4
4,Iowa,36,40.2,83.2,29.8,64.5,0.461,9.2,25.3,0.363,...,19.4,0.749,11.2,24.5,35.7,16.0,7.3,4.3,9.2,16.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,Evansville,30,40.8,59.2,21.0,52.7,0.398,8.2,24.8,0.330,...,12.8,0.708,4.4,22.0,26.4,10.5,5.9,2.0,11.2,14.7
354,Air Force,29,40.0,59.0,21.6,49.6,0.436,7.2,21.6,0.333,...,13.3,0.649,5.5,19.9,25.4,12.5,5.4,3.0,13.5,18.0
355,South Florida,31,39.9,57.5,21.6,57.7,0.374,4.5,17.6,0.252,...,14.7,0.666,10.6,23.9,34.5,10.9,6.2,3.7,12.5,17.1
356,Eastern Illinois,31,40.0,56.3,20.1,50.5,0.398,6.0,18.3,0.326,...,15.9,0.638,6.8,21.5,28.4,11.8,6.3,3.0,16.0,14.5
357,IUPUI,29,40.0,52.4,19.2,50.6,0.380,5.1,17.6,0.292,...,13.3,0.667,9.3,20.7,30.0,10.4,5.7,2.6,16.6,17.7

In [5]:
url = 'https://basketball.realgm.com/ncaa/team-stats/2022/Misc_Stats/Team_Totals/0'
misc = pd.read_html(url)[0]
del misc[misc.columns[0]]

misc = misc.drop(columns = ['Dbl Dbl', 'Tpl Dbl', '40 Pts', '20 Reb', '20 Ast', 
                                         '5 Stl', '5 Blk', 'High Game', 'MOV', 'Techs'])
misc

                  Team    HOB  Ast/TO  Stl/TO  FT/FGA  W's  L's  Win %
0       North Carolina  1.541     1.3     0.4   0.232   29   10  0.744
1                 Duke  1.554     1.6     0.6   0.211   32    7  0.821
2       Morehead State  1.629     1.2     0.4   0.189   23   11  0.676
3             Kentucky  1.534     1.4     0.6   0.203   26    8  0.765
4              Oakland  1.519     1.1     0.7   0.265   20   12  0.625
..                 ...    ...     ...     ...     ...  ...  ...    ...
353  Southern Illinois  1.522     1.1     0.5   0.200   16   15  0.516
354              Omaha  1.434     0.8     0.4   0.209    5   25  0.167
355  Northern Illinois  1.488     0.8     0.5   0.224    9   21  0.300
356       Pennsylvania  1.473     1.1     0.5   0.176   12   16  0.429
357   Florida Atlantic  1.501     1.0     0.6   0.203   19   15  0.559

[358 rows x 8 columns]

In [9]:
temp = pd.merge(averages, advanced, how = 'left', on = ['Team'])
combined = pd.merge(temp, misc, how = 'left', on = ['Team'])
combined

,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,3P%,...,eDiff,Poss,Pace,HOB,Ast/TO,Stl/TO,FT/FGA,W's,L's,Win %
0,Gonzaga,32,39.9,87.2,32.7,62.6,0.521,8.2,22.1,0.370,...,28.2,2381.4,74.6,1.553,1.6,0.6,0.219,28,4,0.875
1,South Dakota State,35,40.2,85.9,30.8,59.1,0.521,9.3,20.9,0.445,...,17.5,2535.2,72.1,1.490,1.4,0.6,0.253,30,5,0.857
2,Arizona,37,40.2,84.0,30.2,61.3,0.492,7.8,22.0,0.352,...,21.5,2733.4,73.5,1.650,1.5,0.5,0.258,33,4,0.892
3,Oral Roberts,31,40.3,83.3,30.2,66.2,0.456,11.6,30.6,0.379,...,12.2,2271.5,72.7,1.388,1.2,0.6,0.170,19,12,0.613
4,Iowa,36,40.2,83.2,29.8,64.5,0.461,9.2,25.3,0.363,...,16.8,2569.9,71.1,1.539,1.7,0.8,0.225,26,10,0.722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,Evansville,30,40.8,59.2,21.0,52.7,0.398,8.2,24.8,0.330,...,-17.6,1972.5,64.4,1.502,0.9,0.5,0.172,6,24,0.200
354,Air Force,29,40.0,59.0,21.6,49.6,0.436,7.2,21.6,0.333,...,-11.0,1850.9,63.9,1.577,0.9,0.4,0.174,11,18,0.379
355,South Florida,31,39.9,57.5,21.6,57.7,0.374,4.5,17.6,0.252,...,-11.2,2063.1,66.7,1.506,0.9,0.5,0.169,8,23,0.258
356,Eastern Illinois,31,40.0,56.3,20.1,50.5,0.398,6.0,18.3,0.326,...,-22.1,2075.6,67.0,1.589,0.7,0.4,0.201,5,26,0.161
357,IUPUI,29,40.0,52.4,19.2,50.6,0.380,5.1,17.6,0.292,...,-22.9,1861.7,64.2,1.544,0.6,0.3,0.176,3,26,0.103

In [10]:
combined.nunique(axis = 0)

Team        358
GP           17
MPG          19
PPG         167
FGM          77
FGA         115
FG%          99
3PM          67
3PA         128
3P%         101
FTM          79
FTA          99
FT%         130
ORB          75
DRB          81
RPG         106
APG          79
SPG          59
BPG          49
TOV          73
PF           76
TS%         107
eFG%        117
Total S%    197
ORB%        150
DRB%        124
TRB%        113
AST%        181
TOV%         82
STL%         81
BLK%        108
PPS           6
FIC40       192
ORtg        178
DRtg        177
eDiff       219
Poss        351
Pace        105
HOB         181
Ast/TO       12
Stl/TO        7
FT/FGA      123
W's          33
L's          26
Win %       137
dtype: int64

In [5]:
url = 'https://basketball.realgm.com/ncaa/teams/2022'
conf = pd.read_html(url)[0]
conf

,School,Nickname,Abrev,Conference,Location,Home Venue
0,Abilene Christian,Wildcats,ACU,WAC,"Abilene, TX",Moody Coliseum
1,Air Force,Falcons,AF,MWC,"Colorado Springs, CO",Clune Arena
2,Akron,Zips,AKR,MAC,"Akron, OH",James A. Rhodes Arena
3,Alabama,Crimson Tide,UA,SEC,"Tuscaloosa, AL",Coleman Coliseum
4,Alabama A&M,Bulldogs,AAMU,SWAC,"Normal, AL",Elmore Gymnasium
...,...,...,...,...,...,...
353,Wright State,Raiders,WRST,Horizon,"Dayton, OH",Nutter Center
354,Wyoming,Cowboys,UW,MWC,"Laramie, WY",Arena-Auditorium
355,Xavier,Musketeers,XAV,Big East,"Cincinnati, OH",Cintas Center
356,Yale,Bulldogs,YALE,Ivy,"New Haven, CT",John J. Lee Amphitheater
357,Youngstown State,Penguins,YSU,Horizon,"Youngstown, OH",Beeghly Center

In [7]:
combined.to_csv('./Data/ncaa22.csv')
conf.to_csv('./Data/conf22.csv')